### ISSUE TITLE
Recieved "Save Parse Error"

### ISSUE THREAD

**Issue by CoulsTech** [MouseyPounds/stardew-predictor#29]
Error output as follows:
Save Parse Error
The app was unable to process the save file. This is most likely a bug with the app, so please let the dev know about it. Details below.

TypeError: Cannot read properties of null (reading 'times')
TypeError: Cannot read properties of null (reading 'times')
    at predictMineChests (https://mouseypounds.github.io/stardew-predictor/stardew-predictor.js?v=5.0.8:7626:68)
    at updateTab (https://mouseypounds.github.io/stardew-predictor/stardew-predictor.js?v=5.0.8:9113:13)
    at HTMLInputElement. (https://mouseypounds.github.io/stardew-predictor/stardew-predictor.js?v=5.0.8:9153:48)
    at Function.each (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:2715)
    at r.fn.init.each (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:1003)
    at updateOutput (https://mouseypounds.github.io/stardew-predictor/stardew-predictor.js?v=5.0.8:9153:30)
    at reader.onload (https://mouseypounds.github.io/stardew-predictor/stardew-predictor.js?v=5.0.8:9208:4)

**Comment by Nullfiller99** [comment]
I have the same exact problem
